[build]
publish = "/public"

[[edge_functions]]
path="/hello"
function = "hello"

[[edge_functions]]
path="/hello-template"
function = "transform-hello-template"

[[redirects]]

from = "/hai"
to = "hello"
status = 301
force = false

from = "/v2/hai"
to = "hello"
status = 301
force = false